---
title: "r-matrices"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Matrix practice

```{r}
# Make a sequence of values from 1 - 10 ----
my_values <- seq(from = 1, to = 10, by = 1)

# Look at it (always) ----
my_values

# convert to matrix ----
my_matrix <- matrix(data = my_values, 
                    nrow = 2, 
                    ncol = 5, 
                    byrow = TRUE)
class(my_matrix)

# Incorrectly declared matrix string ----
#matrix(data = my_values, nrow = 2, ncol = 3, byrow = TRUE)
#matrix(data = my_values, nrow = 3, ncol = 4, byrow = TRUE)
```

## Math with matrices

```{r}
#scalar multiplication ----
4 * my_matrix

# make a 2x5 matrix ----
my_values2 <- seq(from = 21, to = 38)
my_matrix2 <- matrix(my_values2, nrow = 2, byrow = T)
my_matrix2

# Math with the two matrices
#my_matrix + my_matrix2
#my_matrix - my_matrix2
```

## Matrix multiplication

```{r}
# make a couple 2x2 matrices ----
cats <- matrix(data = c(0,4,3,1), nrow = 2, byrow = T)
dogs <- matrix(data = c(6,-3,0,2), nrow = 2, byrow = T)
cats
dogs

# matrix multiplication
cats %*% dogs
```

## Leslie matrix example

```{r}
# create your matrix ----
insect_leslie <- matrix(c(0,0,600,0.2,0,0,0,0.08,0), nrow = 3, ncol =  3, byrow = T)
insect_leslie

#specify an initial condition ----
# insect lifestage populations (year 0)
insect_y0 <- c(12000, 700, 500)

# Find the populations for each life stage at t=1 year
insect_y1 <- insect_leslie %*% insect_y0
insect_y1

# Find the populations for each life stage at t=2 year
insect_y2 <- insect_leslie %*% insect_y1
insect_y2

# Find the populations for each life stage at t=3 year
insect_y3 <- insect_leslie %*% insect_y2
insect_y3

# Find the populations for each life stage at t=4 year
insect_y4 <- insect_leslie %*% insect_y3
insect_y4
```

## Another leslie matrix example

```{r}
# make the tree projection matrix ----
tree_rep <- matrix(c(0,0,5000,0.10,0,0,0,0.06,0.95), nrow = 3, ncol = 3, byrow = T)
tree_rep

# year 0: initial conditions ----
tree_0 <- c(5000, 0, 0)

# year 1 ----
tree_1 <- tree_rep %*% tree_0
tree_1

# year 2 ----
tree_2 <- tree_rep %*% tree_1
tree_2

# year 3 ----
tree_3 <- tree_rep %*% tree_2
tree_3

# year 4 ----
tree_4 <- tree_rep %*% tree_3
tree_4
```

